mercadopago:
  collectorId: COLLECTOR_ID
  clientId: YOUR_CLIENT_ID
  #webhookSecret:
  clientSecret: YOUR_CLIENT_SECRET
  accessToken: ACCESS_TOKEN
  baseUrl: MERCADO_PAGO_BASE_URL
  posExternalId: ''
  redirectUri: ''
spring:
  application:
    name: cars
  datasource:
    password:  ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username:  ${DB_USER}
    url:  ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info # Inclui os endpoints health e info
  endpoint:
    health:
      show-details: always # Mostra detalhes do health check (como status de dependências)