apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-cars
  namespace: dog-cars
  labels:
    app: dog-cars
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-cars
  template:
    metadata:
      labels:
        app: dog-cars
    spec:
      containers:
        - name: dog-cars
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/dog-cars:${IMAGE_TAG}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dog-cars-config
            - secretRef:
                name: dog-cars-secret
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3