apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-cars
  namespace: dog-cars
  labels:
    app: dog-cars
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-cars
  template:
    metadata:
      labels:
        app: dog-cars
    spec:
      containers:
        - name: dog-cars
          image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dog-cars:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DB_NAME
              value: "DB_NAME_PLACEHOLDER"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "DB_USER_PLACEHOLDER"
            - name: DB_PASSWORD
              value: "DB_PASSWORD_PLACEHOLDER"
            - name: DB_URL
              value: "DB_URL_PLACEHOLDER"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5