apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-cars
  namespace: dog-cars
spec:
  template:
    spec:
      containers:
        - name: dog-cars
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/dog-cars:latest
          env:
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_HOST
              value: "${DB_HOST}"